version: '3'

services:
  db:
    container_name: postgres-database
    image: postgres:15
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

#    volumes:
#        - /tmp/database/postgres :/var/lib/postgresql/data

  app:
    container_name: go-app-cubevis
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      - CGO_ENABLED=0
      - GOOS=linux