version: '3'

services:
  db:
    container_name: postgres-database
    image: postgres:15
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

    volumes:
        - /tmp/database/postgres :/var/lib/postgresql/data

  app:
    container_name: go-app-cubevis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - CGO_ENABLED=0
      - GOOS=linux