// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"github.com/google/uuid"
)

type Address struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Address string
	Number  sql.NullString
	ZipCode sql.NullString
	City    string
	State   string
}

type User struct {
	ID       uuid.UUID
	Name     sql.NullString
	Email    string
	Password string
}
