// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
)

type Address struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Address string
	Number  string
	ZipCode string
	City    string
	State   string
}

type Product struct {
	ID    int32
	Name  string
	Value int32
}

type User struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password string
}
